version: '3.8'
services:
  modelserver:
    build: modelserver
    hostname: modelserver.svc
    command: --config_path /models_config.json --port 9001
    restart: always
  restore:
    build: GFPGAN
    ports:
      - 8081:5000
    restart: always
  backend:
    build: backend
    environment:
      - RESTORE_ENABLED=True
      - RESTORE_ADDRESS=restore
      - RESTORE_PORT=5000
      - GRPC_ADDRESS=modelserver.svc
      - GRPC_PORT=9001
    ports:
      - 8080:5000
    restart: always
  frontend:
    build: frontend
    environment:
      - BACKEND_HOSTNAME=backend
      - BACKEND_PORT=5000
      - RESTORE_ADDRESS=restore
      - RESTORE_PORT=5000
    ports:
      - 8000:3000
    restart: always
