apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modelserver
  name: modelserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modelserver
  template:
    metadata:
      labels:
        app: modelserver
    spec:
      containers:
        - args:
            - --config_path
            - /models_config.json
            - --port
            - "9001"
          image: localhost:32000/modelserver:latest
          name: modelserver
          ports:
            - containerPort: 9001
      restartPolicy: Always
